set(DAQ_VERSION 2.0.0)
add_definitions(-DUSE_DAQ122)

if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    if(MSVC)
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(DAQ_LIB_BIT "x64")
        else()
            set(DAQ_LIB_BIT "x86")
        endif()
        message("${DAQ_LIB_BIT}")
        set(DAQ_ROOT_PATH "${CMAKE_SOURCE_DIR}/lib/${CMAKE_SYSTEM_NAME}")
        set(DAQ_ROOT_PATH "${DAQ_ROOT_PATH}/libdaq")
        set(DAQ_THIRD_PARTY_PATH "${DAQ_ROOT_PATH}/third_party")

        set(DAQ_INCLUDE_DIRS "${DAQ_ROOT_PATH}/include" "${DAQ_THIRD_PARTY_PATH}/include")
        set(DAQ_LIBRARIES "${DAQ_ROOT_PATH}/lib/${DAQ_LIB_BIT}/libdaq-${DAQ_VERSION}.lib")
    endif()
else()
    set(DAQ_ROOT_PATH "${CMAKE_SOURCE_DIR}/lib/Linux")
    set(DAQ_ROOT_PATH "${DAQ_ROOT_PATH}/libdaq")
    set(DAQ_THIRD_PARTY_PATH "${DAQ_ROOT_PATH}/third_party")

    set(DAQ_INCLUDE_DIRS "${DAQ_ROOT_PATH}/include" "${DAQ_THIRD_PARTY_PATH}/include")
    set(DAQ_LIBRARIES "${DAQ_ROOT_PATH}/lib/Linux/liblibdaq-${DAQ_VERSION}.so")
endif()

include_directories(${DAQ_INCLUDE_DIRS})
