name: Release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run build script
      run: ./build.sh

    - name: Archive Release Asset
      run: tar -czvf ./dist/DAQ122_Lin_${{ matrix.arch }}.tar.gz -C ./dist DAQ122
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DAQ122_Lin_${{ matrix.arch }}
        path: ./dist/DAQ122_Lin_${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: DAQ122_Lin_arm64

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: DAQ122_Lin_arm64.tar.gz
